CREATE DATABASE School;

USE School;

CREATE TABLE STUDENT (Roll_No INT PRIMARY KEY, Name VARCHAR(280), Marks DECIMAL(5,2), Grade VARCHAR(1) ) ;

INSERT INTO STUDENT (Roll_No, Name, Marks, Grade) VALUES
  (1, 'Sanju', 84.25, 'B'),
  (2, 'Varsha', 81.00, 'B'),
  (3, 'Reshma', 95.50, 'A'),
  (4, 'Abin', 92.00, 'A'),
  (5, 'Adithya', 72.30, 'C');
  
  select * from STUDENT;
  
  ALTER TABLE STUDENT
ADD Contact VARCHAR(10);

DESCRIBE STUDENT;

UPDATE STUDENT
SET Contact = '9874267890'
WHERE Roll_No = 1;
UPDATE STUDENT
SET Contact = '8874129645'
WHERE Roll_No = 2;


UPDATE STUDENT
SET Contact = '7520391220'
WHERE Roll_No = 3;
UPDATE STUDENT
SET Contact = '9654789321'
WHERE Roll_No = 4;
UPDATE STUDENT
SET Contact = '7013643338'
WHERE Roll_No = 5;

ALTER TABLE STUDENT
DROP COLUMN Grade;

RENAME TABLE STUDENT TO CLASSTEN;

SELECT * FROM CLASSTEN;

TRUNCATE TABLE CLASSTEN;

DROP TABLE CLASSTEN;

